pipeline {
    agent any
    stages {
        stage('Custom-filters') {
            steps {
                dir('custom-filters') {
                    // Execute Maven build for custom-filter
                    sh 'mvn clean install -U'
                }
            }
        }
        stage('Payslips') {
            steps {
                dir('payslips') {
                    // Execute Maven build for payslip
                    sh 'mvn clean install -U'
                    sh 'mvn clean install'
                    sh 'java -jar payslips-0.0.1-SNAPSHOT.jar & '
                    sh 'mvn spring-boot:run'
                }
            }
        }
    }
}
def buildNumber = BUILD_NUMBER as int
if (buildNumber > 1) milestone(buildNumber - 1)
milestone(buildNumber)
